name: TEST CD

on:
  push:
    branches:
      - test-cd
    paths:
      - "colin-api/**"
      - "legal-api/**"
      - "queue_services/entity-emailer/**"
      - "queue_services/entity-filer/**"
      - "queue_services/common/**"

jobs:
  test-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check1
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})

      - name: echo
        run: |
          echo ${{ steps.filepath.outputs.commitpath }}
